# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ghann/GHGE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ghann/GHGE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ghann/GHGE/CMakeFiles /home/ghann/GHGE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ghann/GHGE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_program

# Build rule for target.
my_program: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_program
.PHONY : my_program

# fast build rule for target.
my_program/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/build
.PHONY : my_program/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/Engine/PointLight.o: src/Engine/PointLight.cpp.o
.PHONY : src/Engine/PointLight.o

# target to build an object file
src/Engine/PointLight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Engine/PointLight.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Engine/PointLight.cpp.o
.PHONY : src/Engine/PointLight.cpp.o

src/Engine/PointLight.i: src/Engine/PointLight.cpp.i
.PHONY : src/Engine/PointLight.i

# target to preprocess a source file
src/Engine/PointLight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Engine/PointLight.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Engine/PointLight.cpp.i
.PHONY : src/Engine/PointLight.cpp.i

src/Engine/PointLight.s: src/Engine/PointLight.cpp.s
.PHONY : src/Engine/PointLight.s

# target to generate assembly for a file
src/Engine/PointLight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Engine/PointLight.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Engine/PointLight.cpp.s
.PHONY : src/Engine/PointLight.cpp.s

src/Engine/inputManager.o: src/Engine/inputManager.cpp.o
.PHONY : src/Engine/inputManager.o

# target to build an object file
src/Engine/inputManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Engine/inputManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Engine/inputManager.cpp.o
.PHONY : src/Engine/inputManager.cpp.o

src/Engine/inputManager.i: src/Engine/inputManager.cpp.i
.PHONY : src/Engine/inputManager.i

# target to preprocess a source file
src/Engine/inputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Engine/inputManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Engine/inputManager.cpp.i
.PHONY : src/Engine/inputManager.cpp.i

src/Engine/inputManager.s: src/Engine/inputManager.cpp.s
.PHONY : src/Engine/inputManager.s

# target to generate assembly for a file
src/Engine/inputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Engine/inputManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Engine/inputManager.cpp.s
.PHONY : src/Engine/inputManager.cpp.s

src/Engine/playerController.o: src/Engine/playerController.cpp.o
.PHONY : src/Engine/playerController.o

# target to build an object file
src/Engine/playerController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Engine/playerController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Engine/playerController.cpp.o
.PHONY : src/Engine/playerController.cpp.o

src/Engine/playerController.i: src/Engine/playerController.cpp.i
.PHONY : src/Engine/playerController.i

# target to preprocess a source file
src/Engine/playerController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Engine/playerController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Engine/playerController.cpp.i
.PHONY : src/Engine/playerController.cpp.i

src/Engine/playerController.s: src/Engine/playerController.cpp.s
.PHONY : src/Engine/playerController.s

# target to generate assembly for a file
src/Engine/playerController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Engine/playerController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Engine/playerController.cpp.s
.PHONY : src/Engine/playerController.cpp.s

src/Physics/bunnyPhysics.o: src/Physics/bunnyPhysics.cpp.o
.PHONY : src/Physics/bunnyPhysics.o

# target to build an object file
src/Physics/bunnyPhysics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Physics/bunnyPhysics.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Physics/bunnyPhysics.cpp.o
.PHONY : src/Physics/bunnyPhysics.cpp.o

src/Physics/bunnyPhysics.i: src/Physics/bunnyPhysics.cpp.i
.PHONY : src/Physics/bunnyPhysics.i

# target to preprocess a source file
src/Physics/bunnyPhysics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Physics/bunnyPhysics.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Physics/bunnyPhysics.cpp.i
.PHONY : src/Physics/bunnyPhysics.cpp.i

src/Physics/bunnyPhysics.s: src/Physics/bunnyPhysics.cpp.s
.PHONY : src/Physics/bunnyPhysics.s

# target to generate assembly for a file
src/Physics/bunnyPhysics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Physics/bunnyPhysics.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Physics/bunnyPhysics.cpp.s
.PHONY : src/Physics/bunnyPhysics.cpp.s

src/Physics/physicsObject.o: src/Physics/physicsObject.cpp.o
.PHONY : src/Physics/physicsObject.o

# target to build an object file
src/Physics/physicsObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Physics/physicsObject.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Physics/physicsObject.cpp.o
.PHONY : src/Physics/physicsObject.cpp.o

src/Physics/physicsObject.i: src/Physics/physicsObject.cpp.i
.PHONY : src/Physics/physicsObject.i

# target to preprocess a source file
src/Physics/physicsObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Physics/physicsObject.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Physics/physicsObject.cpp.i
.PHONY : src/Physics/physicsObject.cpp.i

src/Physics/physicsObject.s: src/Physics/physicsObject.cpp.s
.PHONY : src/Physics/physicsObject.s

# target to generate assembly for a file
src/Physics/physicsObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Physics/physicsObject.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Physics/physicsObject.cpp.s
.PHONY : src/Physics/physicsObject.cpp.s

src/Physics/shape.o: src/Physics/shape.cpp.o
.PHONY : src/Physics/shape.o

# target to build an object file
src/Physics/shape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Physics/shape.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Physics/shape.cpp.o
.PHONY : src/Physics/shape.cpp.o

src/Physics/shape.i: src/Physics/shape.cpp.i
.PHONY : src/Physics/shape.i

# target to preprocess a source file
src/Physics/shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Physics/shape.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Physics/shape.cpp.i
.PHONY : src/Physics/shape.cpp.i

src/Physics/shape.s: src/Physics/shape.cpp.s
.PHONY : src/Physics/shape.s

# target to generate assembly for a file
src/Physics/shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/Physics/shape.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Physics/shape.cpp.s
.PHONY : src/Physics/shape.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/test.o: test/test.cpp.o
.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... my_program"
	@echo "... tests"
	@echo "... src/Engine/PointLight.o"
	@echo "... src/Engine/PointLight.i"
	@echo "... src/Engine/PointLight.s"
	@echo "... src/Engine/inputManager.o"
	@echo "... src/Engine/inputManager.i"
	@echo "... src/Engine/inputManager.s"
	@echo "... src/Engine/playerController.o"
	@echo "... src/Engine/playerController.i"
	@echo "... src/Engine/playerController.s"
	@echo "... src/Physics/bunnyPhysics.o"
	@echo "... src/Physics/bunnyPhysics.i"
	@echo "... src/Physics/bunnyPhysics.s"
	@echo "... src/Physics/physicsObject.o"
	@echo "... src/Physics/physicsObject.i"
	@echo "... src/Physics/physicsObject.s"
	@echo "... src/Physics/shape.o"
	@echo "... src/Physics/shape.i"
	@echo "... src/Physics/shape.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

